// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsiukqwmzplfuviotnol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzaXVrcXdtenBsZnV2aW90bm9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjAxNjQsImV4cCI6MjA2NDE5NjE2NH0.PBusSMDPvdtWmr05torTy8Tq0QcFjiKmMhu0t3T0AIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);